<?php
declare(strict_types=1);

namespace Sensum\Cms\Media;

use Sensum\Cms\Http\ApiError;

/**
 * Server-side validation and re-encoding of uploaded photos (GD only).
 *
 * Every accepted image is decoded and re-encoded from raw pixels, which
 * strips EXIF/GPS metadata and anything appended to or hidden inside the
 * original file (polyglots, scripts in comments…). Nothing from the upload
 * other than its pixels ever reaches the public folder, and file names are
 * always generated by the server.
 */
final class ImageProcessor
{
    public const MAX_SIDE = 12000;
    public const MAX_PIXELS = 40_000_000;

    private const TYPES = [
        IMAGETYPE_JPEG => ['mime' => 'image/jpeg', 'ext' => ['jpg', 'jpeg']],
        IMAGETYPE_PNG => ['mime' => 'image/png', 'ext' => ['png']],
        IMAGETYPE_WEBP => ['mime' => 'image/webp', 'ext' => ['webp']],
    ];

    /** Throws ApiError for PHP upload failures (size limits, partial uploads…). */
    public static function assertUploadOk(?array $file, int $maxBytes): void
    {
        if (!$file || ($file['error'] ?? UPLOAD_ERR_NO_FILE) === UPLOAD_ERR_NO_FILE) {
            throw ApiError::validation(['file' => 'file_required']);
        }
        $err = (int) $file['error'];
        if ($err === UPLOAD_ERR_INI_SIZE || $err === UPLOAD_ERR_FORM_SIZE) {
            throw ApiError::validation(['file' => 'file_too_large']);
        }
        if ($err === UPLOAD_ERR_PARTIAL) {
            throw ApiError::validation(['file' => 'upload_incomplete']);
        }
        if ($err !== UPLOAD_ERR_OK || !is_uploaded_file((string) $file['tmp_name'])) {
            throw new ApiError(500, 'upload_failed');
        }
        $size = (int) filesize((string) $file['tmp_name']);
        if ($size <= 0) {
            throw ApiError::validation(['file' => 'file_empty']);
        }
        if ($size > $maxBytes) {
            throw ApiError::validation(['file' => 'file_too_large']);
        }
    }

    /** Sanitized original file name, for display only. */
    public static function displayName(string $name): string
    {
        $name = basename(str_replace('\\', '/', $name));
        $name = preg_replace('/[\x00-\x1F\x7F<>:"\/\\\\|?*]+/u', '', $name) ?? '';
        return mb_substr(trim($name), 0, 120);
    }

    /**
     * Validates type/extension/content/dimensions and decodes the image.
     * @return array{img:\GdImage, w:int, h:int, type:int}
     */
    public static function load(string $path, string $originalName, array $min = [1, 1]): array
    {
        $ext = strtolower(pathinfo($originalName, PATHINFO_EXTENSION));
        $allowedExt = array_merge(...array_column(self::TYPES, 'ext'));
        if (!in_array($ext, $allowedExt, true)) {
            throw ApiError::validation(['file' => 'file_type_not_allowed']);
        }

        $finfo = new \finfo(FILEINFO_MIME_TYPE);
        $mime = (string) $finfo->file($path);
        $info = @getimagesize($path);
        if (!$info || !isset(self::TYPES[$info[2]])) {
            throw ApiError::validation(['file' => in_array($mime, array_column(self::TYPES, 'mime'), true) ? 'image_corrupt' : 'file_type_not_allowed']);
        }
        $type = (int) $info[2];
        // Extension, sniffed MIME type and the decoder's own type must all agree.
        if ($mime !== self::TYPES[$type]['mime'] || !in_array($ext, self::TYPES[$type]['ext'], true)) {
            throw ApiError::validation(['file' => 'file_type_mismatch']);
        }

        [$w, $h] = [(int) $info[0], (int) $info[1]];
        if ($w < 1 || $h < 1 || $w > self::MAX_SIDE || $h > self::MAX_SIDE || $w * $h > self::MAX_PIXELS) {
            throw ApiError::validation(['file' => 'image_too_large_pixels']);
        }
        if ($w < $min[0] || $h < $min[1]) {
            // Account for photos taken sideways (EXIF orientation is applied below).
            if (!($h >= $min[0] && $w >= $min[1])) {
                throw ApiError::validation(['file' => 'image_too_small']);
            }
        }
        self::ensureMemory($w, $h);

        // Truncated or damaged files often still "decode" with a warning and
        // a grey/partial picture: treat any decoder warning as corruption.
        $previous = ini_set('gd.jpeg_ignore_warning', '0');
        $warned = false;
        set_error_handler(static function () use (&$warned): bool {
            $warned = true;
            return true;
        });
        try {
            $img = match ($type) {
                IMAGETYPE_JPEG => imagecreatefromjpeg($path),
                IMAGETYPE_PNG => imagecreatefrompng($path),
                IMAGETYPE_WEBP => function_exists('imagecreatefromwebp') ? imagecreatefromwebp($path) : false,
                default => false,
            };
        } finally {
            restore_error_handler();
            if ($previous !== false) {
                ini_set('gd.jpeg_ignore_warning', $previous);
            }
        }
        if (!$img instanceof \GdImage || $warned) {
            if ($img instanceof \GdImage) {
                imagedestroy($img);
            }
            throw ApiError::validation(['file' => 'image_corrupt']);
        }
        if ($type === IMAGETYPE_JPEG) {
            $img = self::applyExifOrientation($img, $path);
        }
        $w = imagesx($img);
        $h = imagesy($img);
        if ($w < $min[0] || $h < $min[1]) {
            imagedestroy($img);
            throw ApiError::validation(['file' => 'image_too_small']);
        }
        return ['img' => $img, 'w' => $w, 'h' => $h, 'type' => $type];
    }

    /** Refuses images whose decoded size would exhaust the PHP memory limit. */
    private static function ensureMemory(int $w, int $h): void
    {
        $limit = self::bytes((string) ini_get('memory_limit'));
        if ($limit <= 0) {
            return; // unlimited
        }
        $need = (int) ($w * $h * 5.2) + 3 * 1600 * 1200 * 4 + 16 * 1024 * 1024;
        if (memory_get_usage(true) + $need > $limit) {
            @ini_set('memory_limit', '384M');
            $limit = self::bytes((string) ini_get('memory_limit'));
            if (memory_get_usage(true) + $need > $limit) {
                throw ApiError::validation(['file' => 'image_too_large_pixels']);
            }
        }
    }

    public static function bytes(string $v): int
    {
        $v = trim($v);
        if ($v === '' || $v === '-1') {
            return -1;
        }
        $n = (int) $v;
        return match (strtolower(substr($v, -1))) {
            'g' => $n * 1024 ** 3,
            'm' => $n * 1024 ** 2,
            'k' => $n * 1024,
            default => $n,
        };
    }

    private static function applyExifOrientation(\GdImage $img, string $path): \GdImage
    {
        if (!function_exists('exif_read_data')) {
            return $img;
        }
        $exif = @exif_read_data($path);
        $o = is_array($exif) ? (int) ($exif['Orientation'] ?? 1) : 1;
        if (in_array($o, [2, 4, 5, 7], true)) {
            imageflip($img, IMG_FLIP_HORIZONTAL);
        }
        $angle = match ($o) {
            3, 4 => 180,
            5, 6 => -90,
            7, 8 => 90,
            default => 0,
        };
        if ($angle !== 0) {
            $rotated = imagerotate($img, $angle, 0);
            if ($rotated instanceof \GdImage) {
                imagedestroy($img);
                return $rotated;
            }
        }
        return $img;
    }

    /**
     * Crop rectangle for a target aspect ratio.
     * $anchor: 'start' (top/left), 'center', 'end' (bottom/right).
     * @return array{0:int,1:int,2:int,3:int} x, y, w, h
     */
    public static function cropRect(int $w, int $h, ?array $ratio, string $anchor): array
    {
        if (!$ratio) {
            return [0, 0, $w, $h];
        }
        $target = $ratio[0] / $ratio[1];
        $f = match ($anchor) { 'start' => 0.0, 'end' => 1.0, default => 0.5 };
        if ($w / $h > $target) {
            $cw = (int) round($h * $target);
            return [(int) round(($w - $cw) * $f), 0, $cw, $h];
        }
        $ch = (int) round($w / $target);
        return [0, (int) round(($h - $ch) * $f), $w, $ch];
    }

    public static function outputExt(): string
    {
        return function_exists('imagewebp') ? 'webp' : 'jpg';
    }

    /**
     * Writes one re-encoded file per requested width (never upscaled).
     * @return list<int> widths actually written
     */
    public static function writeVariants(\GdImage $src, array $rect, array $widths, string $dir, string $base, string $ext): array
    {
        [$x, $y, $cw, $ch] = $rect;
        $written = [];
        foreach (array_unique($widths) as $target) {
            $tw = min((int) $target, $cw);
            if (in_array($tw, $written, true)) {
                continue;
            }
            $th = (int) round($ch * $tw / $cw);
            $dst = imagecreatetruecolor($tw, $th);
            // Flatten any transparency onto the site's dark ink color.
            imagefill($dst, 0, 0, imagecolorallocate($dst, 28, 28, 28));
            imagecopyresampled($dst, $src, 0, 0, $x, $y, $tw, $th, $cw, $ch);
            $final = "{$dir}/{$base}-w{$tw}.{$ext}";
            $tmp = "{$dir}/.tmp-" . bin2hex(random_bytes(6));
            $ok = $ext === 'webp' ? imagewebp($dst, $tmp, 82) : imagejpeg($dst, $tmp, 85);
            imagedestroy($dst);
            if (!$ok || !@rename($tmp, $final)) {
                @unlink($tmp);
                throw new \RuntimeException('image_write_failed');
            }
            @chmod($final, 0644);
            $written[] = $tw;
        }
        return $written;
    }
}
